name: PR

on:
  pull_request:
    branches:
      - master

env:
  DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/postgres

jobs:
  pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Replace .env
        run: mv ./server/.env.example ./server/.env

      - name: Build
        run: |
          cd web
          yarn && yarn build
          cd ..
          cp -r web/build/ server/static
          cd server
          cargo build
